site_name: Rust Web Programming

theme:
  name: material
  locale: ja
  font:
    text: 'Noto Sans Japanese'

nav:
  - 序文: index.md
  - '1章 - Rust Web開発入門':
    - '1 - Rust Web開発入門':               1_QuickIntroduction/index.md
    - '1.1 - 技術要件':                     1_QuickIntroduction/TechnicalRequirements.md
    - '1.2 - なぜRustは革命的なのか？':     1_QuickIntroduction/WhyIsRustRevolutionary.md
  - '2章 - RustでWebアプリケーションをデザインする':
    - '2 - RustでWebアプリケーションをデザインする':      2_DesigningYourWebApplicationInRust/index.md
    - '2.1 - 技術要件':                                   2_DesigningYourWebApplicationInRust/TechnicalRequirements.md
    - '2.2 - Cargoによるソフトウェアプロジェクトの管理':  2_DesigningYourWebApplicationInRust/ManagingASoftwareProjectWithCargo.md
    - '2.3 - コードの構造化':                             2_DesigningYourWebApplicationInRust/StructuringCode.md
    - '2.4 - 環境との相互作用':                           2_DesigningYourWebApplicationInRust/InteractingWithTheEnvironment.md
    - '2.5 - まとめ':                                     2_DesigningYourWebApplicationInRust/Summary.md
  - '3章 - HTTPリクエストの取り扱い':
    - '3 - HTTPリクエストの取り扱い':                         3_HandlingHTTPRequests/index.md
    - '3.1 - 技術要件':                                       3_HandlingHTTPRequests/TechnicalRequirements.md
    - '3.2 - Actix Webフレームワークの紹介':                  3_HandlingHTTPRequests/IntroducingTheActixWebFramework.md
    - '3.3 - 基本的なActix Webサーバーの立ち上げ':            3_HandlingHTTPRequests/LaunchingABasicActixWebServer.md
    - '3.4 - クロージャを理解する':                           3_HandlingHTTPRequests/UnderstandingClosures.md
    - '3.5 - 非同期プログラミングの理解':                     3_HandlingHTTPRequests/UnderstandingAsynchronousProgramming.md
    - '3.6 - asyncとawaitを理解する':                         3_HandlingHTTPRequests/UnderstandingAsyncAndAwait.md
    - '3.7 - Webプログラミングでasyncとawaitを探求する':      3_HandlingHTTPRequests/ExploringAsyncAndAwaitWithWebProgramming.md
    - '3.8 - Actix Webフレームワークを使用したビューの管理':  3_HandlingHTTPRequests/ManagingViewsUsingTheActixWebFramework.md
    - '3.9 - まとめ':                                         3_HandlingHTTPRequests/Summary.md
    # - '3.10 - 質問':
    # - '3.11 - 回答':
  - '4章 - HTTPリクエストの処理':
    - '4 - HTTPリクエストの処理':                           4_ProcessingHTTPRequests/index.md
    - '4.1 - 技術要件':                                     4_ProcessingHTTPRequests/TechnicalRequirements.md
    - '4.2 - コードを定着させるための初期設定について知る': 4_ProcessingHTTPRequests/GettingToKnowTheInitialSetupForFusingCode.md
    - '4.3 - ビューにパラメータを渡す':                     4_ProcessingHTTPRequests/PassingParametersIntoViews.md
    - '4.4 - JSONシリアライズのためのマクロの使用':         4_ProcessingHTTPRequests/UsingMacrosForJSONSerialization.md
    - '4.5 - ビューからデータを抽出する':                   4_ProcessingHTTPRequests/ExtractingDataFromViews.md
    - '4.6 - まとめ':                                       4_ProcessingHTTPRequests/Summary.md
  - '5章 - ブラウザでコンテンツを表示する':
    - '5 - ブラウザでコンテンツを表示する':                                   5_DisplayingContentInTheBrowser/index.md
    - '5.1 - 技術要件':                                                       5_DisplayingContentInTheBrowser/TechnicalRequirements.md
    - '5.2 - Rustを使ったHTML、CSS、JavaScriptのサービス提供':                5_DisplayingContentInTheBrowser/ServingHTMLCSSAndJavaScriptUsingRust.md
    - '5.3 - HTMLにJavaScriptを注入する':                                     5_DisplayingContentInTheBrowser/InjectingJavaScriptIntoHTML.md
    - '5.4 - HTMLにCSSを組み込む':                                            5_DisplayingContentInTheBrowser/InjectingCSSIntoHTML.md
    - '5.5 - コンポーネントの継承':                                           5_DisplayingContentInTheBrowser/InheritingComponents.md
    - '5.6 - Reactアプリを作成する':                                          5_DisplayingContentInTheBrowser/CreatingAReactApp.md
    - '5.7 - ReactでAPIを呼び出す':                                           5_DisplayingContentInTheBrowser/MakingAPICallsInReact.md
    - '5.8 - Reactのカスタムコンポーネントの作成':                            5_DisplayingContentInTheBrowser/CreatingCustomComponentsInReact.md
    - '5.9 - CSSをReactに持ち込む':                                           5_DisplayingContentInTheBrowser/LiftingCSSIntoReact.md
    - '5.10 - Reactアプリケーションをデスクトップアプリケーションへ変換する': 5_DisplayingContentInTheBrowser/ConvertingOurReactApplicationIntoADesktopApplication.md
    - '5.11 - まとめ':                                                        5_DisplayingContentInTheBrowser/Summary.md
  - '6章 - PostgreSQLによるデータ永続化':
    - '6 - PostgreSQLによるデータ永続化':   6_DataPersistenceWithPostgreSQL/index.md
    - '6.1 - 技術要件':                     6_DataPersistenceWithPostgreSQL/TechnicalRequirements.md
    - '6.2 - PostgreSQLデータベースの構築': 6_DataPersistenceWithPostgreSQL/BuildingOurPostgreSQLDatabase.md
    - '6.3 - DieselでPostgreSQLに接続する': 6_DataPersistenceWithPostgreSQL/ConnectingToPostgreSQLWithDiesel.md
    - '6.4 - アプリをPostgreSQLに接続する': 6_DataPersistenceWithPostgreSQL/ConnectingOurAppToPostgreSQL.md
    - '6.5 - データベースへの挿入':         6_DataPersistenceWithPostgreSQL/InsertingIntoTheDatabase.md
    - '6.6 - アプリケーションを構成する':   6_DataPersistenceWithPostgreSQL/ConfiguringOurApplication.md
    - '6.7 - データベース接続プールの構築': 6_DataPersistenceWithPostgreSQL/BuildingADatabaseConnectionPool.md
    - '6.8 - まとめ':                       6_DataPersistenceWithPostgreSQL/Summary.md
  - '7章 - ユーザーセッションの管理':
    - '7 - ユーザーセッションの管理':           7_ManagingUserSessions/index.md
    - '7.1 - 技術要件':                         7_ManagingUserSessions/TechnicalRequirements.md
    - '7.2 - ユーザーモデルを作成する':         7_ManagingUserSessions/CreatingOurUserModel.md
    - '7.3 - ユーザーを認証する':               7_ManagingUserSessions/AuthenticatingOurUsers.md
    - '7.4 - ユーザーセッションの管理':         7_ManagingUserSessions/ManagingUserSessions.md
    - '7.5 - 認証要件のクリーンアップ':         7_ManagingUserSessions/CleaningUpAuthenticationRequirements.md
    - '7.6 - 認証トークンの有効期限を設定する': 7_ManagingUserSessions/ConfiguringExpirationOfAuthTokens.md
    - '7.7 - フロントエンドに認証を追加する':   7_ManagingUserSessions/AddingAuthenticationIntoOurFrontend.md
    - '7.8 - まとめ':                           7_ManagingUserSessions/Summary.md
  - '8章 - RESTfulサービスの構築':
    - '8.1 - RESTfulサービスの構築':                8_BuildingRESTfulServices/index.md
    - '8.2 - 技術要件':                             8_BuildingRESTfulServices/TechnicalRequirements.md
    - '8.3 - RESTfulサービスとは何ですか？':        8_BuildingRESTfulServices/WhatAreRESTfulServices.md
    - '8.4 - レイヤーシステムをマッピングする':     8_BuildingRESTfulServices/MappingOurLayeredSystem.md
    - '8.5 - 統一されたインターフェースの構築':     8_BuildingRESTfulServices/BuildingAUniformInterface.md
    - '8.6 - ステートレス化の実施':                 8_BuildingRESTfulServices/ImplementingStatelessness.md
    - '8.7 - 当社サーバーのトラフィックを記録する': 8_BuildingRESTfulServices/LoggingOurServerTraffic.md
    - '8.8 - キャッシング':                         8_BuildingRESTfulServices/Caching.md
    - '8.9 - コードオンデマンド':                   8_BuildingRESTfulServices/CodeOnDemand.md
    - '8.10 - まとめ':                              8_BuildingRESTfulServices/Summary.md

markdown_extensions:
  - admonition
  - fontawesome_markdown
  - codehilite
  - tables
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - "css/extra.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
